<?php

$admin_fields_set 	= is_field_group_exists( 'E-consult - Admin Instellingen' );
$user_fields_set	= is_field_group_exists( 'E-consult - Algemene informatie' );
$hidden_fields_set 	= is_field_group_exists( 'E-consult - Verborgen Instellingen' );

if( function_exists('register_field_group') && !$admin_fields_set ):

register_field_group(array (
	'key' => 'group_54c901b21fda4',
	'title' => 'E-consult - Admin Instellingen',
	'fields' => array (
		array (
			'key' => 'field_54c901c76633e',
			'label' => 'E-mailadres',
			'name' => 'econsult_admin_emailaddress',
			'prefix' => '',
			'type' => 'text',
			'instructions' => 'Vul het e-mailadres in van de ontvanger. Wanneer dit niet ingevuld is, zal het terugvallen op de e-mail uit Instellingen > Lezen.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'naam@emailadres.nl',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54c902066633f',
			'label' => 'Bevestigingspagina',
			'name' => 'econsult_confirmation_page',
			'prefix' => '',
			'type' => 'post_object',
			'instructions' => 'Pagina voor de bevestiging van het inzenden van de e-consult.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'page',
			),
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'id',
			'ui' => 1,
		),
		array (
			'key' => 'field_54c9027466340',
			'label' => 'E-mail naar beheerder',
			'name' => 'econsult_email_to_admin',
			'prefix' => '',
			'type' => 'wysiwyg',
			'instructions' => 'E-mail naar de beheerder van de website. De e-mail zal in de stijl van de website verzonden worden.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
		),
		array (
			'key' => 'field_54c9029866341',
			'label' => 'E-mail naar aanvrager',
			'name' => 'econsult_email_to_sender',
			'prefix' => '',
			'type' => 'wysiwyg',
			'instructions' => 'E-mail naar de aanvrager van het e-consult. De e-mail zal in de stijl van de website verzonden worden.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
		),
		array (
			'key' => 'field_54ca5b6a696be',
			'label' => 'Update e-mail',
			'name' => 'econsult_update_email',
			'prefix' => '',
			'type' => 'wysiwyg',
			'instructions' => 'E-mail die aangeeft dat er een update is op het consult.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-instellingen-e-consult',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_54c8fbe67c657',
	'title' => 'E-consult - Algemene informatie',
	'fields' => array (
		array (
			'key' => 'field_54c8fbf76e995',
			'label' => 'Geslacht',
			'name' => 'econsult_gender',
			'prefix' => '',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'man' => 'Man',
				'vrouw' => 'Vrouw',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_54c8fc136e996',
			'label' => 'Voornaam',
			'name' => 'econsult_first_name',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Voornaam',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54c8fc316e997',
			'label' => 'Achternaam',
			'name' => 'econsult_last_name',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Achternaam',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54c8fc476e998',
			'label' => 'Geboortedatum',
			'name' => 'econsult_date_of_birth',
			'prefix' => '',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array (
			'key' => 'field_54c8fc5a6e999',
			'label' => 'Telefoonnummer',
			'name' => 'econsult_phone',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Telefoonnummer',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'read_only' => '',
			'mask' => '',
			'function' => 'none',
			'pattern' => '',
			'message' => 'Validation failed.',
			'unique' => 'non-unique',
			'unique_statuses' => array (
				0 => 'publish',
				1 => 'future',
			),
			'drafts' => 1,
			'key' => 'field_54c8fc7c6e99a',
			'label' => 'E-mailadres',
			'name' => 'econsult_emailaddress',
			'prefix' => '',
			'type' => 'validated_field',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'sub_field' => array (
				'type' => 'email',
				'key' => 'field_54c8fc7c6e99a',
				'name' => 'econsult_emailaddress',
				'_name' => 'econsult_emailaddress',
				'id' => 'field_54c8fc7c6e99a',
				'value' => '',
				'field_group' => '',
				'parent' => '',
				'save' => '',
				'default_value' => '',
				'placeholder' => 'E-mailadres',
				'prepend' => '',
				'append' => '',
				'prefix' => 'acf',
			),
		),
		array (
			'key' => 'field_54c9ff05839c9',
			'label' => 'Vraag',
			'name' => 'econsult_question',
			'prefix' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Vraag',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54c900bb23aa1',
			'label' => 'Afbeelding',
			'name' => 'econsult_image',
			'prefix' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_54e74eb9d45f4',
			'label' => 'Afbeelding 2',
			'name' => 'econsult_image_2',
			'prefix' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_54e74ebad45f5',
			'label' => 'Afbeelding 3',
			'name' => 'econsult_image_3',
			'prefix' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_54e74c7d2de35',
			'label' => 'Door op verzenden te klikken, geeft u aan bekend te zijn met de informatie op deze pagina',
			'name' => '',
			'prefix' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'esc_html' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'econsult',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'custom_fields',
		3 => 'discussion',
		4 => 'revisions',
		5 => 'author',
		6 => 'format',
		7 => 'page_attributes',
		8 => 'featured_image',
		9 => 'categories',
		10 => 'tags',
		11 => 'send-trackbacks',
	),
));

register_field_group(array (
	'key' => 'group_54c9fd349e8a7',
	'title' => 'E-consult - Verborgen Instellingen',
	'fields' => array (
		array (
			'key' => 'field_54c9fd4c2924f',
			'label' => 'GUID',
			'name' => 'econsult_guid',
			'prefix' => '',
			'type' => 'text',
			'instructions' => 'Dit is de geheime code die gegenereerd wordt bij een aanvraag voor een econsult.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'econsult',
			),
			array (
				'param' => 'user_type',
				'operator' => '==',
				'value' => 'administrator',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));


endif;

function is_field_group_exists( $value, $type = 'post_title' ) {

    $exists = false;

    if( $field_groups = get_posts( array('post_type'=>'acf-field-group' ) ) ) {

        foreach ( $field_groups as $field_group ) {

            if ( $field_group->$type == $value ) {
                $exists = true;
            }
        }
    }

    return $exists;

}